### PR TITLE
CMO-445 : ignoring Unit cases to reach and validate "Deploy to Pre-int

### PR DESCRIPTION
**Pull request by JGovindaraj**
and Intergration" step in Jenkin

### JIRA Issue Link
- [Verify CD Pipeline](https://osi-cwds.atlassian.net/browse/CMO-445)

### CODE REVIEW

**Comment by SashaKyz** [comment]
retest this please

**Comment by SashaKyz** [comment]
retest this please

**Comment by SashaKyz** [comment]
retest this please

**Comment by JGovindaraj** [comment]
CMO-445 - Added / Updated Junit test cases.

**Pull request merged**
